version: '3.7'

services:
  phd2_exporter:
    user: "${DOCKER_USER_ID}:${DOCKER_GROUP_ID}"
    image: phd2_exporter
    build:
      target: dev
      args:
        USER: phd2_exporter
        USER_ID: ${DOCKER_USER_ID}
        GROUP_ID: ${DOCKER_GROUP_ID}
    volumes:
      - ${PWD}:/app
      - ${PWD}/.bash_history:/home/phd2_exporter/.bash_history
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9187:9187
