name: Create and publish a phd2_exporter docker image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}:latest

jobs:
  build-and-push-image:
    name: Build, test, and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build tests
        run: |
          docker build --target tester -t phd2_exporter_tests .

      - name: Run tests
        run: |
          docker run phd2_exporter_tests
  
      - name: Build release
        run: |
          docker build --target release -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .

      - name: Publish
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
